[package]
name = "example-db-prisma-orm"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "prisma-cli"
path = "src/bin/prisma.rs"

[dependencies]
prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust", branch="main", default-features = false, features = ["migrations", "sqlite"]}
prisma-client-rust-cli = { git = "https://github.com/Brendonovich/prisma-client-rust", branch="main", default-features = false, features = ["migrations", "sqlite"]}

serde = { workspace = true, features = ["derive"] }
salvo = { workspace = true }
tokio = { workspace = true, features = ["full"] }
async-trait .workspace = true

tracing .workspace = true
tracing-subscriber .workspace = true